<project xmlns="http://maven.apache.org/POM/4.0.0" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
    <modelVersion>4.0.0</modelVersion>
    <parent>
        <groupId>io.todolist</groupId>
        <artifactId>be-springboot</artifactId>
        <version>1.0.0</version>
        <relativePath>../pom.xml</relativePath>
    </parent>

    <artifactId>common-core</artifactId>
    <name>todolist-common-core</name>
    <url>https://github.com/AleDeP10/TodoList/tree/main/be-springboot/common-core</url>
    <description>Shared library module containing common utilities, configurations, and base classes used across
        ToDoList microservices.
    </description>

    <properties>
        <java.version>17</java.version>
    </properties>

    <dependencies>
        <!-- Common-contracts: shared DTOs, messages, errors and dependencies -->
        <dependency>
            <groupId>io.todolist</groupId>
            <artifactId>common-contracts</artifactId>
            <version>1.0.0</version>
        </dependency>

        <!-- Spring Boot starter for core Spring features -->
        <dependency>
            <groupId>org.springframework.boot</groupId>
            <artifactId>spring-boot-starter</artifactId>
        </dependency>

        <!-- Spring Boot Starter Data JPA for database access with JPA/Hibernate -->
        <dependency>
            <groupId>org.springframework.boot</groupId>
            <artifactId>spring-boot-starter-data-jpa</artifactId>
        </dependency>

        <!-- Jakarta Persistence API: JPA specification -->
        <dependency>
            <groupId>jakarta.persistence</groupId>
            <artifactId>jakarta.persistence-api</artifactId>
        </dependency>

        <!-- PostgreSQL Driver: JDBC driver for PostgreSQL database -->
        <dependency>
            <groupId>org.postgresql</groupId>
            <artifactId>postgresql</artifactId>
        </dependency>

        <!-- Spring WebMVC for CORS and web configuration -->
        <dependency>
            <groupId>org.springframework</groupId>
            <artifactId>spring-webmvc</artifactId>
        </dependency>

        <!-- Flyway: Database migration tool used during testing to apply schema changes on the in-memory H2 database -->
        <dependency>
            <groupId>org.flywaydb</groupId>
            <artifactId>flyway-core</artifactId>
        </dependency>

        <!-- Spring Boot starter for testing -->
        <dependency>
            <groupId>org.springframework.boot</groupId>
            <artifactId>spring-boot-starter-test</artifactId>
            <scope>test</scope>
        </dependency>
    </dependencies>
</project>