spring.application.name=common

# Enable showing SQL statements in the logs
spring.jpa.show-sql=true

# Format the SQL statements for better readability in logs
spring.jpa.properties.hibernate.format_sql=true

# Controls when Spring Boot initializes the database using SQL scripts.
# 'always' means it will run the scripts on every application startup.
spring.sql.init.mode=always

# Expose the health, info, and prometheus endpoints for management
management.endpoints.web.exposure.include=health,info,prometheus

# Always show detailed health information
management.endpoint.health.show-details=always

# Enable health probes for readiness and liveness checks
management.endpoint.health.probes.enabled=true

# Disable flyway for environments different from test
spring.flyway.enabled=false

# Redis server hostname or IP address
spring.redis.host=localhost

# Redis server port number
spring.redis.port=6379

# Connection timeout in milliseconds for Redis connections
spring.redis.timeout=2000

# Password for authenticating with Redis server (if required)
spring.redis.password=

# Lettuce client specific configuration: pool max idle connections
spring.redis.lettuce.pool.max-idle=8

# Lettuce client specific configuration: pool min idle connections
spring.redis.lettuce.pool.min-idle=0

# Lettuce client specific configuration: pool max active connections
spring.redis.lettuce.pool.max-active=8

# Lettuce client specific configuration: pool max wait time in milliseconds
spring.redis.lettuce.pool.max-wait=1000

# Enable or disable Redis repositories (Spring Data Redis)
spring.data.redis.repositories.enabled=true

# Time to live (TTL) for cache entries in seconds (if using Redis as cache)
spring.cache.redis.time-to-live=600000

# Enable or disable Redis cache statistics collection
spring.cache.redis.enable-statistics=false
