import type { Metadata } from "next";
// import { Geist, Geist_Mono } from "next/font/google";
import { Inter } from "next/font/google";
import "react-toastify/dist/ReactToastify.css";
import "@/lib/styles/globals.css";
import { Providers } from "./providers";
import ToastListener from "@/components/feedback/ToastManager";


const inter = Inter({
  subsets: ["latin"],
  variable: "--font-inter",
});
/*const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});*/

export const metadata: Metadata = {
  title: "ToDoList - Next.js implementation",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en" className="dark">
      {/* className={`${geistSans.variable} ${geistMono.variable} antialiased`} */}
      <body
        className={`${inter.variable} antialiased`}
      >
        <Providers>
          {children}
          <ToastListener />
        </Providers>
      </body>
    </html>
  );
}
