import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "@/styles/globals.css";
import "react-toastify/dist/ReactToastify.css";
import { Providers } from "./providers"; 
import { ToastContainer } from "react-toastify";
import ToastListener from "@/lib/ToastListener";
import { LangProvider } from "@/lib/i18n";
import { ViewProvider } from "@/lib/view";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "TodoList - nextjs implementation",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en" className="dark">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <Providers>
          <LangProvider>
            <ViewProvider>
              {children}
              <ToastContainer />
              <ToastListener />
            </ViewProvider>
          </LangProvider>
        </Providers>
      </body>
    </html>
  );
}
